//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 06:49:48 PM CET 
//


package de.fhtrier.gdw.commons.tiled.tmx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tmxLayer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tmxLayer">
 *   &lt;complexContent>
 *     &lt;extension base="{}tmxLayerBase">
 *       &lt;sequence>
 *         &lt;element name="data" type="{}tmxData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tmxLayer", propOrder = {
    "data"
})
public class TmxLayer
    extends TmxLayerBase
{

    @XmlElement(required = true)
    protected TmxData data;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link TmxData }
     *     
     */
    public TmxData getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmxData }
     *     
     */
    public void setData(TmxData value) {
        this.data = value;
    }

}
