//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 06:49:48 PM CET 
//

package de.fhtrier.gdw.commons.tiled.tmx;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tmxMap complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tmxMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{}tmxProperties"/>
 *         &lt;element name="tileset" type="{}tmxTileSet" maxOccurs="unbounded"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="layer" type="{}tmxLayer"/>
 *           &lt;element name="objectgroup" type="{}tmxObjectGroup"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orientation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tilewidth" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tileheight" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tmxMap", propOrder = { "properties", "tileset",
		"layerOrObjectgroup" })
public class TmxMap {

	@XmlElement(required = true)
	protected TmxProperties properties;
	@XmlElement(required = true)
	protected List<TmxTileSet> tileset;
	@XmlElements({ @XmlElement(name = "layer", type = TmxLayer.class),
			@XmlElement(name = "objectgroup", type = TmxObjectGroup.class) })
	protected List<TmxLayerBase> layerOrObjectgroup;
	@XmlAttribute(name = "version", required = true)
	protected String version;
	@XmlAttribute(name = "orientation", required = true)
	protected String orientation;
	@XmlAttribute(name = "width", required = true)
	protected int width;
	@XmlAttribute(name = "height", required = true)
	protected int height;
	@XmlAttribute(name = "tilewidth", required = true)
	protected int tilewidth;
	@XmlAttribute(name = "tileheight", required = true)
	protected int tileheight;

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return possible object is {@link TmxProperties }
	 * 
	 */
	public TmxProperties getProperties() {
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *            allowed object is {@link TmxProperties }
	 * 
	 */
	public void setProperties(TmxProperties value) {
		this.properties = value;
	}

	/**
	 * Gets the value of the tileset property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the tileset property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTileset().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TmxTileSet }
	 * 
	 * 
	 */
	public List<TmxTileSet> getTileset() {
		if (tileset == null) {
			tileset = new ArrayList<TmxTileSet>();
		}
		return this.tileset;
	}

	/**
	 * Gets the value of the layerOrObjectgroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the layerOrObjectgroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLayerOrObjectgroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TmxLayer }
	 * {@link TmxObjectGroup }
	 * 
	 * 
	 */
	public List<TmxLayerBase> getLayerOrObjectgroup() {
		if (layerOrObjectgroup == null) {
			layerOrObjectgroup = new ArrayList<TmxLayerBase>();
		}
		return this.layerOrObjectgroup;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the orientation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrientation() {
		return orientation;
	}

	/**
	 * Sets the value of the orientation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrientation(String value) {
		this.orientation = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 */
	public int getWidth() {
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 */
	public void setWidth(int value) {
		this.width = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 */
	public int getHeight() {
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 */
	public void setHeight(int value) {
		this.height = value;
	}

	/**
	 * Gets the value of the tilewidth property.
	 * 
	 */
	public int getTilewidth() {
		return tilewidth;
	}

	/**
	 * Sets the value of the tilewidth property.
	 * 
	 */
	public void setTilewidth(int value) {
		this.tilewidth = value;
	}

	/**
	 * Gets the value of the tileheight property.
	 * 
	 */
	public int getTileheight() {
		return tileheight;
	}

	/**
	 * Sets the value of the tileheight property.
	 * 
	 */
	public void setTileheight(int value) {
		this.tileheight = value;
	}

}
