//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 06:49:48 PM CET 
//

package de.fhtrier.gdw.commons.tiled.tmx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tmxPointList complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tmxPointList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="points" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tmxPointList")
public class TmxPointList {

	@XmlAttribute(name = "points")
	protected String points;

	/**
	 * Gets the value of the points property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPoints() {
		return points;
	}

	/**
	 * Sets the value of the points property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPoints(String value) {
		this.points = value;
	}

}
