package de.fhtrier.gdw.ss2013.input;

public enum InputAction {
    MOVE_RIGHT, MOVE_LEFT, JUMP, ACTION, TOGGLE_ALIEN, SHOOT, TARGET, PREV_ABILITY, NEXT_ABILITY, USE_ABILITY,
    CURSOR_LEFT, CURSOR_RIGHT, CURSOR_UP, CURSOR_DOWN
    
}
